M48
; DRILL file KiCad 10.0.0 date 2026-05-31T18:54:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-31T18:54:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
%
G90
G05
T1
X105.525Y-93.375
X109.775Y-93.375
X111.225Y-93.375
X115.475Y-93.375
T2
X112.1Y-101.2
M30
