M48
; DRILL file {KiCad 8.0.5} date 2024-12-17T02:27:56+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-17T02:27:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X5.8094Y-3.8496
X5.8094Y-4.0772
T2
X4.8161Y-4.2691
X4.9343Y-4.2691
M30
