M48
; DRILL file {KiCad 8.0.5} date 2024-11-08T04:09:29+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-08T04:09:29+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X5.8096Y-3.8496
X5.8096Y-4.0772
T2
X5.1671Y-4.2684
X5.2852Y-4.2684
T3
X5.1783Y-3.9421
M30
