M48
; DRILL file {KiCad 8.0.5} date 2024-10-05T23:36:12+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-05T23:36:12+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X7.9907Y-2.8008
X7.9907Y-3.0283
T2
X7.3343Y-3.2441
X7.4524Y-3.2441
T3
X7.3622Y-2.9075
M30
