M48
; DRILL file {KiCad 9.0.0} date 2025-06-12T14:50:29+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-12T14:50:29+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.600
%
G90
G05
T1
X147.567Y-97.78
X147.567Y-103.56
T2
X127.91Y-92.67
X132.16Y-92.67
X134.465Y-92.685
X138.715Y-92.685
T3
X131.53Y-100.13
M30
